### ISSUE TITLE
Textures sometimes not loading

### ISSUE THREAD

**Issue by AndyCat1811** [P3pp3rF1y/SophisticatedStorage#136]
When I open my modpack that includes this mod, it is a gamble everytime to know if the textures will load or not.  Is there a way to make sure they load everytime?

**Comment by P3pp3rF1y** [comment]
I am not aware of any issue like that. This is very likely an issue of another mod causing this. Have you tried just sophisticated storage by itself?

**Comment by AndyCat1811** [comment]
It seems to work when it is alone, but I've compared both log files of when it loads correctly and when it doesn't and when the mod is not loading, this exception occurs when registering recipes.

Here is the important part in the log file.

```
[16:01:53] [Render thread/INFO]: Building recipe registry...
[16:01:54] [Render thread/INFO]: Building recipe registry took 20.97 ms
[16:01:54] [Render thread/INFO]: Registering recipes: jei:minecraft ...
[16:01:54] [Render thread/INFO]: Registering recipes: jei:minecraft took 364.4 ms
[16:01:54] [Render thread/INFO]: Registering recipes: sophisticatedstorage:default ...
[16:01:54] [Render thread/INFO]: Registering recipes: sophisticatedstorage:default ...
[16:01:54] [Render thread/ERROR]: Caught an error from mod plugin: class net.p3pp3rf1y.sophisticatedstorage.compat.jei.StoragePlugin sophisticatedstorage:default
java.lang.IndexOutOfBoundsException: Index: 4, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:756) ~[?:?]
	at java.util.ArrayList.add(ArrayList.java:481) ~[?:?]
	at net.minecraft.core.NonNullList.add(NonNullList.java:61) ~[client-1.18.2-20220404.173914-srg.jar%23140!/:?]
	at net.p3pp3rf1y.sophisticatedstorage.compat.jei.TierUpgradeRecipesMaker.lambda$getCraftingRecipes$0(TierUpgradeRecipesMaker.java:44) ~[sophisticatedstorage-1.18.2-0.6.16.274.jar%23130!/:1.18.2-0.6.16.274]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.p3pp3rf1y.sophisticatedstorage.compat.jei.TierUpgradeRecipesMaker.lambda$getCraftingRecipes$1(TierUpgradeRecipesMaker.java:31) ~[sophisticatedstorage-1.18.2-0.6.16.274.jar%23130!/:1.18.2-0.6.16.274]
	at net.p3pp3rf1y.sophisticatedcore.compat.jei.ClientRecipeHelper.lambda$getAndTransformAvailableItemGroupRecipes$2(ClientRecipeHelper.java:42) ~[sophisticatedcore-1.18.2-0.5.37.202.jar%23129!/:1.18.2-0.5.37.202]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.p3pp3rf1y.sophisticatedcore.compat.jei.ClientRecipeHelper.lambda$getAndTransformAvailableItemGroupRecipes$3(ClientRecipeHelper.java:40) ~[sophisticatedcore-1.18.2-0.5.37.202.jar%23129!/:1.18.2-0.5.37.202]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.p3pp3rf1y.sophisticatedcore.compat.jei.ClientRecipeHelper.getAndTransformAvailableItemGroupRecipes(ClientRecipeHelper.java:40) ~[sophisticatedcore-1.18.2-0.5.37.202.jar%23129!/:1.18.2-0.5.37.202]
	at net.p3pp3rf1y.sophisticatedstorage.compat.jei.TierUpgradeRecipesMaker.getCraftingRecipes(TierUpgradeRecipesMaker.java:29) ~[sophisticatedstorage-1.18.2-0.6.16.274.jar%23130!/:1.18.2-0.6.16.274]
	at net.p3pp3rf1y.sophisticatedstorage.compat.jei.StoragePlugin.registerRecipes(StoragePlugin.java:140) ~[sophisticatedstorage-1.18.2-0.6.16.274.jar%23130!/:1.18.2-0.6.16.274]
	at mezz.jei.common.load.PluginLoader.lambda$createRecipeManager$9(PluginLoader.java:188) ~[jei-1.18.2-forge-10.2.1.1002.jar%23104!/:10.2.1.1002]
	at mezz.jei.common.load.PluginCaller.callOnPlugins(PluginCaller.java:25) ~[jei-1.18.2-forge-10.2.1.1002.jar%23104!/:10.2.1.1002]
	at mezz.jei.common.load.PluginLoader.createRecipeManager(PluginLoader.java:188) ~[jei-1.18.2-forge-10.2.1.1002.jar%23104!/:10.2.1.1002]
	at mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:86) ~[jei-1.18.2-forge-10.2.1.1002.jar%23104!/:10.2.1.1002]
	at mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:84) ~[jei-1.18.2-forge-10.2.1.1002.jar%23104!/:10.2.1.1002]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.18.2-forge-10.2.1.1002.jar%23104!/:10.2.1.1002]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.18.2-forge-10.2.1.1002.jar%23104!/:10.2.1.1002]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1270) ~[client-1.18.2-20220404.173914-srg.jar%23140!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23140!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.18.2-20220404.173914-srg.jar%23140!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23140!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23140!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23140!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23140!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23140!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.2-20220404.173914-srg.jar%23140!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23140!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23140!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.0.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```

**Comment by AndyCat1811** [comment]
Also to add some details : 
- I use the last 1.18.2 version
- I noticed that only barrel textures are missing, the chests, shulker boxes and all other items from this mod like the upgrade seem to be always ok.
- In the last couple of days I counted and the barrel textures have loaded 2 times out of 12.

**Comment by P3pp3rF1y** [comment]
I have fixed the issue with barrel textures not loading in dev so this is going to be fixed with the next release

**Comment by P3pp3rF1y** [comment]
fixed in latest release on curseforge
