### ISSUE TITLE
Netherite Shulker Box crafted crashes game

### ISSUE THREAD

**Issue by CharitableClas** [P3pp3rF1y/SophisticatedStorage#15]
[2022-05-20-2.log](https://github.com/P3pp3rF1y/SophisticatedStorage/files/8746221/2022-05-20-2.log)

**Comment by CharitableClas** [comment]
This is the actual error code

[22:24:10] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@86b4adc, suppressing error
java.lang.ArrayIndexOutOfBoundsException: Index 108 out of bounds for length 108
	at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
	at net.minecraft.core.NonNullList.set(NonNullList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.increaseSize(InventoryHandler.java:313) ~[sophisticatedcore-1.18.2-0.1.0.19.jar%23122!/:1.18.2-0.1.0.19]
	at net.p3pp3rf1y.sophisticatedstorage.block.StorageWrapper.increaseSize(StorageWrapper.java:388) ~[sophisticatedstorage-1.18.2-0.0.11.26.jar%23123!/:1.18.2-0.0.11.26]
	at net.p3pp3rf1y.sophisticatedstorage.block.ShulkerBoxBlock.lambda$setPlacedBy$5(ShulkerBoxBlock.java:128) ~[sophisticatedstorage-1.18.2-0.0.11.26.jar%23123!/:1.18.2-0.0.11.26]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.p3pp3rf1y.sophisticatedstorage.block.ShulkerBoxBlock.m_6402_(ShulkerBoxBlock.java:112) ~[sophisticatedstorage-1.18.2-0.0.11.26.jar%23123!/:1.18.2-0.0.11.26]
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:77) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:589) ~[forge-1.18.2-40.1.16-universal.jar%23134!/:?]
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:222) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:359) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:987) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[22:24:10] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: Index 108 out of bounds for length 108
	at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
	at net.minecraft.core.NonNullList.set(NonNullList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.increaseSize(InventoryHandler.java:313) ~[sophisticatedcore-1.18.2-0.1.0.19.jar%23122!/:1.18.2-0.1.0.19]
	at net.p3pp3rf1y.sophisticatedstorage.block.StorageWrapper.increaseSize(StorageWrapper.java:388) ~[sophisticatedstorage-1.18.2-0.0.11.26.jar%23123!/:1.18.2-0.0.11.26]
	at net.p3pp3rf1y.sophisticatedstorage.block.ShulkerBoxBlock.lambda$setPlacedBy$5(ShulkerBoxBlock.java:128) ~[sophisticatedstorage-1.18.2-0.0.11.26.jar%23123!/:1.18.2-0.0.11.26]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.p3pp3rf1y.sophisticatedstorage.block.ShulkerBoxBlock.m_6402_(ShulkerBoxBlock.java:112) ~[sophisticatedstorage-1.18.2-0.0.11.26.jar%23123!/:1.18.2-0.0.11.26]
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:77) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.world.item.ItemStack.lambda$useOn$5(ItemStack.java:223) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:238) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:223) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105262_(MultiPlayerGameMode.java:313) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1566) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1846) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1663) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1019) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.16.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]

**Comment by P3pp3rF1y** [comment]
I can recreate so I will need instructions on how this shulker box was crafted. And does this happen in single player or on multiplayer server?

**Comment by coaber** [comment]
Happens to me also. I initially crafted a diamond one, added filter and stack upgrades, then remembered there's a netherite variant so i made that, and when placed down, it would crash my game.

**Comment by CharitableClas** [comment]
> I can recreate so I will need instructions on how this shulker box was crafted. And does this happen in single player or on multiplayer server?

Happens on Single Player World opened up to LAN. and not opened up. Also I used the normal chest the shulker shells and the redstone torch for the normal recipe the start one. Then just upgraded all the way to netherite through the recipes that follow.

**Comment by P3pp3rF1y** [comment]
This should be fixed in the latest version.
