### ISSUE TITLE
Crash dedicated server on launch with Chipped, NoClassDefFoundError

### ISSUE THREAD

**Issue by gardenappl** [P3pp3rF1y/SophisticatedStorage#310]
In singleplayer it works fine, using REI and REI Plugin Compatibilies. On a dedicated server, however, the latest version crashes with this error:
```
[26Nov2023 12:48:37.452] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: sophisticatedstor
age, class net.p3pp3rf1y.sophisticatedstorage.SophisticatedStorage
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.3.jar%23113!/:?]
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.3.jar%23112!/:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: mezz/jei/api/registration/IRecipeCatalystRegistration
        at net.p3pp3rf1y.sophisticatedstorage.compat.chipped.ChippedCompat.init(ChippedCompat.java:49) ~[sophisticatedstorage-1.20.1-0.8.58.644.jar%23109!/:1.20.1-0.8.58.644]
        at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
        at net.p3pp3rf1y.sophisticatedstorage.init.ModCompat.initCompats(ModCompat.java:60) ~[sophisticatedstorage-1.20.1-0.8.58.644.jar%23109!/:1.20.1-0.8.58.644]
        at net.p3pp3rf1y.sophisticatedstorage.SophisticatedStorage.<init>(SophisticatedStorage.java:37) ~[sophisticatedstorage-1.20.1-0.8.58.644.jar%23109!/:1.20.1-0.8.58.644]
        ... 14 more
Caused by: java.lang.ClassNotFoundException: mezz.jei.api.registration.IRecipeCatalystRegistration
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.p3pp3rf1y.sophisticatedstorage.compat.chipped.ChippedCompat.init(ChippedCompat.java:49) ~[sophisticatedstorage-1.20.1-0.8.58.644.jar%23109!/:1.20.1-0.8.58.644]
        at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
        at net.p3pp3rf1y.sophisticatedstorage.init.ModCompat.initCompats(ModCompat.java:60) ~[sophisticatedstorage-1.20.1-0.8.58.644.jar%23109!/:1.20.1-0.8.58.644]
        at net.p3pp3rf1y.sophisticatedstorage.SophisticatedStorage.<init>(SophisticatedStorage.java:37) ~[sophisticatedstorage-1.20.1-0.8.58.644.jar%23109!/:1.20.1-0.8.58.644]
        ... 14 more
```
Same with Sophisticated Backpacks

**Comment by gardenappl** [comment]
This happens with and without REI btw

**Comment by P3pp3rF1y** [comment]
Fixed in the latest release on CF
