### ISSUE TITLE
Storage controller broken causing dupe bug (All of fabric 7)

### ISSUE THREAD

**Issue by Hapseleg** [P3pp3rF1y/SophisticatedStorage#424]
Hi there,

(AOF7 uses an unofficial port of sophisticated storage, so maybe this is the wrong place to post this?)
![image](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/12915302/f0f2b65d-d518-4f38-91d4-72bf1a52440c)

I'm not sure whats causing it but the first time i placed down a "storage controller" next to a barrel I get this error:

```
[11:53:49] [Server thread/ERROR]: [WTHIT] Caught unhandled exception : [class mcp.mobius.waila.plugin.textile.provider.ItemStorageProvider$$Lambda$48285/0x000000080527f3a8
player hapseleg] java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.transfer.v1.storage.StorageView.isResourceBlank()" because "view" is null
[11:53:49] [Server thread/ERROR]: [WTHIT] java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.transfer.v1.storage.StorageView.isResourceBlank()" because "view" is null
	at mcp.mobius.waila.plugin.textile.provider.ItemStorageProvider.addItem(ItemStorageProvider.java:75)
	at mcp.mobius.waila.plugin.textile.provider.ItemStorageProvider.lambda$appendData$0(ItemStorageProvider.java:52)
	at mcp.mobius.waila.access.DataWriter.lambda$send$1(DataWriter.java:81)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at mcp.mobius.waila.access.DataWriter.send(DataWriter.java:75)
	at mcp.mobius.waila.network.Packets.lambda$initServer$10(Packets.java:166)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

If I place a hopper on top of the controller and place a stackable item in the hopper, the item will stay in the hopper and dupe itself into the barrel, if the item is not stackable it will dupe itself one time, then move into the barrel.

![2024-05-24_12 17 33](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/12915302/26c9dd4d-044b-48cf-8af1-3797226763d3)
![2024-05-24_12 17 44](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/12915302/0b6735d6-dfce-4380-b824-6db6dcf5aecb)
![2024-05-24_12 17 49](https://github.com/P3pp3rF1y/SophisticatedStorage/assets/12915302/216d4057-2436-4104-8e61-491c6911230f)

**Comment by Aikoyori** [comment]
https://github.com/Salandora/SophisticatedStorage ?

**Comment by P3pp3rF1y** [comment]
closing as this is a bug in the unofficial fabric version
