### ISSUE TITLE
Game Crash:  

### ISSUE THREAD

**Issue by matthew1429** [P3pp3rF1y/SophisticatedStorage#43]
I'm unable to join my multiplayer server at this time due to this particular mod crashing.  Every time I rejoin it crashes again.  

The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Pose stack not empty
Exit Code: -1

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 7/18/22, 7:57 PM
Description: Unexpected error

java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.client.renderer.LevelRenderer.m_109588_(LevelRenderer.java:1420) ~[client-1.19-20220607.102129-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinLevelRenderer,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1225) ~[client-1.19-20220607.102129-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinLevelRenderer,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19-20220607.102129-srg.jar%23163!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19-20220607.102129-srg.jar%23163!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23163!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23163!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23163!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.100.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.LevelRenderer.m_109588_(LevelRenderer.java:1420) ~[client-1.19-20220607.102129-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinLevelRenderer,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1225) ~[client-1.19-20220607.102129-srg.jar%23163!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supermartijn642corelib.mixins.json:LevelRendererMixin,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinLevelRenderer,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19-20220607.102129-srg.jar%23163!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Kanan_Jarus'/71970, l='ClientLevel', x=-725.25, y=63.20, z=-342.06]]
	Chunk stats: 3025, 463
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,98,33), Section: (at 0,2,1 in 0,6,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 25548381 game time, 12820551 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:449) ~[client-1.19-20220607.102129-srg.jar%23163!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2182) ~[client-1.19-20220607.102129-srg.jar%23163!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:691) ~[client-1.19-20220607.102129-srg.jar%23163!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23163!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.100.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default, VanillaTweaks_r415187.zip

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 861633648 bytes (821 MiB) / 2315255808 bytes (2208 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GT 1030
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1d01
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34706.36
	Virtual memory used (MB): 23541.01
	Swap memory total (MB): 18432.00
	Swap memory used (MB): 1224.08
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.19-forge-41.0.100
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: GeForce GT 1030/PCIe/SSE2 GL version 3.2.0 NVIDIA 456.71, NVIDIA Corporation
	Window size: 1360x697
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/VanillaTweaks_r415187.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.0.100.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.0.100.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.0.100.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.0.100.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.0.100.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.0.3-mc1.19.jar                      |Macaw's Bridges               |mcwbridges                    |2.0.3               |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.19-2.0.0.120.jar             |TerraBlender                  |terrablender                  |2.0.0.120           |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.19-3.17.13.628.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19-3.17.13.628    |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.19-1.5.1.jar                     |Guard Villagers               |guardvillagers                |1.19-1.5.1          |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.19-17.0.0.143.jar                 |Biomes O' Plenty              |biomesoplenty                 |17.0.0.143          |DONE      |Manifest: NOSIGNATURE
		bigbrain-1.6.1.jar                                |Big Brain                     |bigbrain                      |1.6.1               |DONE      |Manifest: NOSIGNATURE
		sophisticatedstorage-1.19-0.3.7.65.jar            |Sophisticated Storage         |sophisticatedstorage          |1.19-0.3.7.65       |DONE      |Manifest: NOSIGNATURE
		jei-1.19-forge-11.0.0.222.jar                     |Just Enough Items             |jei                           |11.0.0.222          |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.19-forge-mc1.19.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19              |DONE      |Manifest: NOSIGNATURE
		portablemobs-1.1.0a-forge-mc1.19.jar              |Portable Mobs                 |portablemobs                  |1.1.0a              |DONE      |Manifest: NOSIGNATURE
		forge-1.19-41.0.100-universal.jar                 |Forge                         |forge                         |41.0.100            |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		sophisticatedcore-1.19-0.3.9.63.jar               |Sophisticated Core            |sophisticatedcore             |1.19-0.3.9.63       |DONE      |Manifest: NOSIGNATURE
		mavm-1.1.0-mc1.19.jar                             |More Axolotl Variants Mod     |mavm                          |1.1.0               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.19-v2a.jar                |CosmeticArmorReworked         |cosmeticarmorreworked         |1.19-v2a            |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		Patchouli-1.19-75.jar                             |Patchouli                     |patchouli                     |1.19-75             |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.9.jar                     |GeckoLib                      |geckolib3                     |3.1.9               |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.19-FORGE-2.0.8.jar                    |Croptopia                     |croptopia                     |2.0.8               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.19-5.8.5rc5-forge.jar                |Journeymap                    |journeymap                    |5.8.5rc5            |DONE      |Manifest: NOSIGNATURE
		citadel-1.12.6-1.19.jar                           |Citadel                       |citadel                       |1.12.6              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.19.3.jar                              |Alex's Mobs                   |alexsmobs                     |1.19.3              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 6e011aec-7b6e-4d2d-82bd-6c7a7b155a1f
	FML: 41.0
	Forge: net.minecraftforge:41.0.100

**Comment by P3pp3rF1y** [comment]
please check existing issues when creating new ones, there's already one create for this #42
