### ISSUE TITLE
When using Smelting upgrade. it causes it to fully unable to reboot server 

### ISSUE THREAD

**Issue by Pineappleguy03** [P3pp3rF1y/SophisticatedStorage#44]
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "java.lang.ref.WeakReference.get()" because "net.p3pp3rf1y.sophisticatedcore.util.RecipeHelper.world" is null
	at net.p3pp3rf1y.sophisticatedcore.util.RecipeHelper.getWorld(RecipeHelper.java:54) ~[sophisticatedcore-1.18.2-0.3.6.53.jar%23127!/:1.18.2-0.3.6.53] {re:mixin,re:classloading,pl:mixin:APP:polymorph_integrations.mixins.json:sophisticatedbackpacks.AccessorRecipeHelper,pl:mixin:A}
	at net.p3pp3rf1y.sophisticatedcore.util.RecipeHelper.getCookingRecipe(RecipeHelper.java:173) ~[sophisticatedcore-1.18.2-0.3.6.53.jar%23127!/:1.18.2-0.3.6.53] {re:mixin,re:classloading,pl:mixin:APP:polymorph_integrations.mixins.json:sophisticatedbackpacks.AccessorRecipeHelper,pl:mixin:A}
	at net.p3pp3rf1y.sophisticatedcore.upgrades.cooking.AutoCookingUpgradeWrapper.lambda$new$2(AutoCookingUpgradeWrapper.java:57) ~[sophisticatedcore-1.18.2-0.3.6.53.jar%23127!/:1.18.2-0.3.6.53] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.upgrades.cooking.AutoCookingUpgradeWrapper.lambda$tryPullingGetUnsucessful$4(AutoCookingUpgradeWrapper.java:154) ~[sophisticatedcore-1.18.2-0.3.6.53.jar%23127!/:1.18.2-0.3.6.53] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.util.InventoryHelper.iterate(InventoryHelper.java:192) ~[sophisticatedcore-1.18.2-0.3.6.53.jar%23127!/:1.18.2-0.3.6.53] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.upgrades.cooking.AutoCookingUpgradeWrapper.tryPullingGetUnsucessful(AutoCookingUpgradeWrapper.java:153) ~[sophisticatedcore-1.18.2-0.3.6.53.jar%23127!/:1.18.2-0.3.6.53] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.upgrades.cooking.AutoCookingUpgradeWrapper.tryPullingInput(AutoCookingUpgradeWrapper.java:132) ~[sophisticatedcore-1.18.2-0.3.6.53.jar%23127!/:1.18.2-0.3.6.53] {re:classloading}
	at net.p3pp3rf1y.sophisticatedcore.upgrades.cooking.AutoCookingUpgradeWrapper.tick(AutoCookingUpgradeWrapper.java:110) ~[sophisticatedcore-1.18.2-0.3.6.53.jar%23127!/:1.18.2-0.3.6.53] {re:classloading}
	at net.p3pp3rf1y.sophisticatedstorage.block.StorageBlockEntity.lambda$serverTick$4(StorageBlockEntity.java:227) ~[sophisticatedstorage-1.18.2-0.3.4.49.jar%23128!/:1.18.2-0.3.4.49] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.p3pp3rf1y.sophisticatedstorage.block.StorageBlockEntity.serverTick(StorageBlockEntity.java:227) ~[sophisticatedstorage-1.18.2-0.3.4.49.jar%23128!/:1.18.2-0.3.4.49] {re:classloading}
	at net.p3pp3rf1y.sophisticatedstorage.block.StorageBlockBase.lambda$getTicker$5(StorageBlockBase.java:92) ~[sophisticatedstorage-1.18.2-0.3.4.49.jar%23128!/:1.18.2-0.3.4.49] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:beefix:Level,re:classloading,pl:accesstransformer:B,xf:fml:beefix:Level,pl:mixin:APP:radium.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:radium.mixins.json:world.block_entity_retrieval.WorldMixin,pl:mixin:APP:radium.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:radium.mixins.json:world.inline_block_access.WorldMixin,pl:mixin:APP:radium.mixins.json:world.inline_height.WorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:radium.mixins.json:ai.nearby_entity_tracking.ServerWorldAccessor,pl:mixin:APP:radium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:radium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:radium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:radium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23148!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

**Comment by P3pp3rF1y** [comment]
update your sophisticated core and potentially storage as well as a result - this issue was fixed almost 10 days ago. And please try to look for these updates before reporting.
