### ISSUE TITLE
(1.21.1 Neoforge) Game crashes because of Cannot get config value before config is loaded

### ISSUE THREAD

**Issue by ModernGamingWorld** [P3pp3rF1y/SophisticatedStorage#562]
[23Dec2024 13:03:50.769] [Render thread/ERROR] [net.neoforged.bus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot get config value before config is loaded.
	Index: 3
	Listeners:
		0: net.neoforged.bus.EventListenerFactory$addAttribComponent/0x00000296fa13c000@1783c60c
		1: net.neoforged.bus.EventListenerFactory$eventInitScreenEvent/0x00000296fb9fc000@7dcadb11
		2: net.neoforged.bus.EventListenerFactory$onInitTitleScreen/0x00000296f93dcc00@1172dc2c
		3: fuzs.bettermodsbutton.neoforge.client.BetterModsButtonNeoForgeClient$$Lambda/0x00000296f9751c40@1cdf5ac3
		4: com.github.L_Ender.lionfishapi.client.event.LFClientEvent$$Lambda/0x00000296fa230a78@49c10777
		5: net.neoforged.bus.EventListenerFactory$onGuiOpened/0x00000296fa420c00@743a337
		6: net.neoforged.bus.EventListenerFactory$onScreenDrawPost/0x00000296fa429c00@e79a675
		7: net.neoforged.bus.EventListenerFactory$onScreenInit/0x00000296fa438800@2540e6f8
		8: net.neoforged.bus.EventListenerFactory$onScreenInit/0x00000296fa760000@2254cdc0
		9: net.neoforged.bus.EventListenerFactory$screenRender/0x00000296facb4c00@389498a6
		10: net.neoforged.bus.EventListenerFactory$onInitGuiPost/0x00000296fadd1400@7b1ddbcf
		11: team.creative.solonion.client.SOLOnionClient$$Lambda/0x00000296fb00b378@68576e39
		12: net.neoforged.bus.EventListenerFactory$handleResolutionChange/0x00000296fb140000@59489572
		13: net.neoforged.bus.EventListenerFactory$onScreenInit/0x00000296fb5a8800@5d767956
		14: twilightforest.client.event.ClientEvents$$Lambda/0x00000296fb78a7e0@626993ae
		15: twilightforest.client.event.ClientEvents$$Lambda/0x00000296fb78c8d8@636cf109
		16: net.blay09.mods.balm.neoforge.event.NeoForgeBalmClientEvents$$Lambda/0x00000296fbe78800@4911b7bf
		17: net.neoforged.bus.EventListenerFactory$guiPostInit/0x00000296fcde3c00@41bb9bf6
java.lang.IllegalStateException: Cannot get config value before config is loaded.
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.base.Preconditions.checkState(Preconditions.java:512)
	at TRANSFORMER/neoforge@21.1.90/net.neoforged.neoforge.common.ModConfigSpec$ConfigValue.getRaw(ModConfigSpec.java:1235)
	at TRANSFORMER/neoforge@21.1.90/net.neoforged.neoforge.common.ModConfigSpec$ConfigValue.get(ModConfigSpec.java:1222)
	at TRANSFORMER/bettermodsbutton@21.1.0/fuzs.bettermodsbutton.neoforge.client.BetterModsButtonNeoForgeClient.setCollapsedBrandingControl(BetterModsButtonNeoForgeClient.java:58)
	at TRANSFORMER/bettermodsbutton@21.1.0/fuzs.bettermodsbutton.neoforge.client.BetterModsButtonNeoForgeClient.lambda$registerEventHandlers$2(BetterModsButtonNeoForgeClient.java:53)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.init(Screen.java:320)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.setScreen(Minecraft.java:1057)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.<init>(Minecraft.java:615)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:214)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136)
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124)
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32)
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)

[23Dec2024 13:03:50.929] [Render thread/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID de794f2b-4c13-43a8-b1e7-7d41d4c705c8
[23Dec2024 13:03:50.937] [Render thread/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 951cfd9b-dee8-4a99-9697-4407365422ed

[crash-2024-12-23_13.03.50-client.txt](https://github.com/user-attachments/files/18232573/crash-2024-12-23_13.03.50-client.txt)

**Comment by P3pp3rF1y** [comment]
I don't see anything related to sophisticated in this crash log other than the fact that it's one of the mods on the list. Why don you think it's caused by sophisticated storage?

**Comment by P3pp3rF1y** [comment]
actually looking at the stack trace more it's clear that the exception is coming from a call in `bettermodsbutton` mod so you would want to report to them.
